# EnviroAnalyzer - Report Generation
# Usage: Rscript generate_report.R <json_input> <output_format>
# Input JSON: Assessment data and metadata
# Output: PDF or DOCX report file path

args <- commandArgs(trailingOnly = TRUE)

# Check required packages
required_packages <- c("jsonlite", "rmarkdown", "knitr")
missing_packages <- required_packages[!sapply(required_packages, requireNamespace, quietly = TRUE)]

if (length(missing_packages) > 0) {
  cat(sprintf('{"success":false,"error":"Missing packages: %s. Install with: install.packages(c(\'jsonlite\', \'rmarkdown\', \'knitr\'))"}', 
              paste(missing_packages, collapse = ", ")))
  quit(status = 1)
}

library(jsonlite)
library(rmarkdown)
library(knitr)

tryCatch({
  if (length(args) < 2) {
    stop("Usage: generate_report.R <json_input> <output_format>")
  }
  
  input <- fromJSON(args[1])
  output_format <- tolower(args[2]) # "pdf" or "docx"
  
  # Extract data
  report_title <- input$title %||% "Environmental Compliance Report"
  regulation_name <- input$regulation %||% "QCVN"
  assessment_date <- input$date %||% format(Sys.Date(), "%Y-%m-%d")
  results <- input$results
  summary_stats <- input$summary
  
  # Determine output directory
  output_dir <- input$output_dir %||% tempdir()
  timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
  
  # Create temporary Rmd file
  rmd_content <- sprintf('
---
title: "%s"
subtitle: "Regulation: %s"
date: "%s"
output:
  %s:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(knitr)
```

# Executive Summary

This report presents the environmental compliance assessment results against **%s**.

**Assessment Date:** %s

## Quick Statistics

| Metric | Value |
|--------|-------|
| Total Parameters | %d |
| Passing | %d |
| Warning | %d |
| Failing | %d |
| Compliance Rate | %.1f%% |

---

# Detailed Results

```{r results_table}
results_df <- data.frame(
  Parameter = c(%s),
  Unit = c(%s),
  Mean = c(%s),
  Limit = c(%s),
  Status = c(%s),
  Percent_of_Limit = c(%s)
)
kable(results_df, col.names = c("Parameter", "Unit", "Mean Value", "Limit", "Status", "%%  of Limit"))
```

---

# Methodology

The compliance assessment follows Vietnamese national technical regulations (QCVN). Each parameter is evaluated against its specified limit:

- **Pass**: Mean value is within 80%% of the limit
- **Warning**: Mean value is between 80%% and 100%% of the limit  
- **Fail**: Mean value exceeds the limit

---

# Recommendations

Based on the assessment results:

1. Parameters marked as **Fail** require immediate attention and remediation measures.
2. Parameters marked as **Warning** should be monitored closely and preventive actions considered.
3. Regular monitoring schedules should be maintained to ensure continued compliance.

---

*Report generated by EnviroAnalyzer Pro*
', 
    report_title,
    regulation_name, 
    assessment_date,
    ifelse(output_format == "pdf", "pdf_document", "word_document"),
    regulation_name,
    assessment_date,
    summary_stats$total %||% length(results),
    summary_stats$pass %||% sum(sapply(results, function(r) r$status == "Pass")),
    summary_stats$warning %||% sum(sapply(results, function(r) r$status == "Warning")),
    summary_stats$fail %||% sum(sapply(results, function(r) r$status == "Fail")),
    (summary_stats$pass %||% 0) / (summary_stats$total %||% 1) * 100,
    paste0('"', sapply(results, function(r) r$parameterName), '"', collapse = ", "),
    paste0('"', sapply(results, function(r) r$unit), '"', collapse = ", "),
    paste(sapply(results, function(r) round(r$meanValue, 2)), collapse = ", "),
    paste(sapply(results, function(r) r$limit), collapse = ", "),
    paste0('"', sapply(results, function(r) r$status), '"', collapse = ", "),
    paste(sapply(results, function(r) round(r$percentOfLimit, 1)), collapse = ", ")
  )
  
  # Write Rmd to temp file
  rmd_file <- file.path(tempdir(), paste0("report_", timestamp, ".Rmd"))
  writeLines(rmd_content, rmd_file)
  
  # Determine output file extension
  output_ext <- ifelse(output_format == "pdf", ".pdf", ".docx")
  output_file <- file.path(output_dir, paste0("EnviroReport_", timestamp, output_ext))
  
  # Render report
  rmarkdown::render(
    input = rmd_file,
    output_file = output_file,
    quiet = TRUE
  )
  
  # Clean up temp Rmd
  unlink(rmd_file)
  
  result <- list(
    success = TRUE,
    format = output_format,
    output_file = output_file,
    file_size = file.info(output_file)$size,
    generated_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%S")
  )
  
  cat(toJSON(result, auto_unbox = TRUE))
  
}, error = function(e) {
  error_result <- list(
    success = FALSE,
    error = as.character(e$message)
  )
  cat(toJSON(error_result, auto_unbox = TRUE))
  quit(status = 1)
})
